spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://k4c106.p.ssafy.io:3306/pet?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
    #하이버네이트가 실행하는 모든 SQL문을 콘솔로 출력해 준다.
    show-sql: true
    hibernate:
      #콘솔에 출력되는 JPA 실행 쿼리를 가독성있게 표현한다. 
      format_sql: true
      ddl-auto: update

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
              
server:
  port: 8888
  servlet:
    context-path: /pet

#AWS
cloud:
  aws:
    credentials:
      accessKey: AKIAW6HKVCPWQNML6AGE
      secretKey: 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
    stack:
      auto: false

# AWS S3 Service bucket
    s3:
      bucket: komubucket
      url: https://s3.ap-northeast-2.amazonaws.com/komubucket
    region:
      static: ap-northeast-2

#My-batis
mybatis:
  type-aliases-package: com.ssafy.pet.dto, com.ssafy.pet.util
  mapper-locations: mapper/**/*.xml